<a href="https://colab.research.google.com/github/TileshwarGupta/TileshwarGupta/blob/main/linea_regresssion_part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:

import pandas as pd
import matplotlib.pyplot as plt
import pickle
from ydata_profiling import ProfileReport
import numpy as np

In [8]:
df = pd.read_csv('advertising.csv')

In [9]:
df


TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

[200 rows x 4 columns]

In [10]:
df.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [11]:
df.tail()

TV  Radio  Newspaper  Sales
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

In [12]:
df.describe()

TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   15.130500
std     85.854236   14.846809   21.778621    5.283892
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   11.000000
50%    149.750000   22.900000   25.750000   16.000000
75%    218.825000   36.525000   45.100000   19.050000
max    296.400000   49.600000  114.000000   27.000000

In [13]:
ProfileReport(df)

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]


100%|██████████| 4/4 [00:00<00:00, 155.40it/s]


Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [14]:
pf = ProfileReport(df)

In [15]:
pf.to_file("report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]


100%|██████████| 4/4 [00:00<00:00, 313.77it/s]


Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [16]:
x = df[['TV']]

In [17]:
x

TV
0    230.1
1     44.5
2     17.2
3    151.5
4    180.8
..     ...
195   38.2
196   94.2
197  177.0
198  283.6
199  232.1

[200 rows x 1 columns]

In [18]:
y = df.Sales

In [19]:
y

0      22.1
1      10.4
2      12.0
3      16.5
4      17.9
       ... 
195     7.6
196    14.0
197    14.8
198    25.5
199    18.4
Name: Sales, Length: 200, dtype: float64

In [20]:
from sklearn.linear_model import LinearRegression
linear = LinearRegression()

In [21]:
linear

LinearRegression()

In [22]:
linear.fit(x,y)

LinearRegression()

In [23]:
linear.intercept_

np.float64(6.974821488229891)

In [24]:
linear.coef_

array([0.05546477])

In [25]:
file = 'linear_reg.sav'
pickle.dump(linear,open(file,'wb'))

In [26]:
linear.predict([[45]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([9.47073616])

In [27]:
l = [4,5,6,7,89,34,45,67,23]


In [28]:
for i in l:
  print(linear.predict([[i]]))

[7.19668057]
[7.25214534]
[7.30761011]
[7.36307488]
[11.91118606]
[8.86062368]
[9.47073616]
[10.69096111]
[8.25051121]


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/

In [29]:
m =0
b = 0
learning_rate = 0.001
for i in range(len(x)):

  x1 = x.iloc[i]
  y1 = y.iloc[i]

  guess = m*x1 + b
  error = y1 - guess
  m -= error * x1 * learning_rate
  b -= error * learning_rate
  print(error)

TV    22.1
Name: 0, dtype: float64
TV    236.713945
dtype: float64
TV    280.905279
dtype: float64
TV    3115.29825
dtype: float64
TV    89050.772132
dtype: float64
TV    144457.246977
dtype: float64
TV    1.026600e+06
dtype: float64
TV    9.242139e+06
dtype: float64
TV    1.022545e+07
dtype: float64
TV    2.549102e+08
dtype: float64
TV    3.451144e+09
dtype: float64
TV    6.019002e+10
dtype: float64
TV    3.142983e+11
dtype: float64
TV    2.017012e+12
dtype: float64
TV    4.436192e+13
dtype: float64
TV    1.811719e+15
dtype: float64
TV    2.463235e+16
dtype: float64
TV    5.722125e+17
dtype: float64
TV    1.128393e+19
dtype: float64
TV    1.390487e+20
dtype: float64
TV    4.679539e+21
dtype: float64
TV    2.477168e+23
dtype: float64
TV    7.902911e+23
dtype: float64
TV    1.604671e+25
dtype: float64
TV    2.326295e+26
dtype: float64
TV    4.792014e+27
dtype: float64
TV    1.826380e+29
dtype: float64
TV    6.573408e+30
dtype: float64
TV    3.994930e+32
dtype: float64
TV    7.130972e+33

In [30]:
def gd(x,y,n):
  m = 6
  c = 3
  alpha = 0.8
  len = x.shape[0]
  for r in range(n):
    y_pred = m*x + c
    cost=(1/len)*((y_pred-y)**2).sum()
    print('cost is ',cost)
    m=m-(-alpha/len)*((y-y_pred)*x).sum()
    c=c-(-alpha/len)*((y-y_pred).sum())
    print('m,c is',m,c)
    if cost<1:
        plt.scatter(x,y)
        plt.plot(x,y_pred)

In [31]:
import pickle
file = 'linear_reg.sav'
pickle.dump(linear,open(file,'wb'))

In [32]:
saved_model = pickle.load(open(file,'rb'))

In [33]:
saved_model.predict([[45]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([9.47073616])

In [35]:
linear.score(x,y)

0.8121757029987414